
name: Deploy to ping.pub

on:
  push:
    branches: [ main ]
  # pull_request:
  #   branches: [ master ]

jobs:
  deploy:
    name: Ping deploy
    runs-on: mainnet 
    steps:
    - name: Environment
      run:  export NODE_OPTIONS="--max_old_space_size=4096"
      
    - name: Git Checkout Latest
      uses: actions/checkout@v3   
      with:
        submodules: recursive
        
    - name: Clean Repository
      run: rm -rf explorer

    - name: Setup config
      run: cp -rf chains explorer/chains

    - name: Setup config
      run: ls explorer
      
    - name: Build
      run: cd explorer && yarn && yarn build

    - name: Deploy
      run: cp -rf explorer/dist/* /var/www/html/
